language: c
compiler:
- gcc

before-install:
- sudo apt-get update
install:
- sudo apt-get install build-essential libssl-dev flex bison
script: "./configure && make && make install"

notifications:
  irc: "ircs://irc.chatfreedom.us:6697#sIRCd"
  template:
      - "%{repository_slug} - %{commit} : %{author}): %{message}"
      - "Build details : %{build_url}"
