name: CI

on:
  push:
    branches: 
      - master
      - beta
    paths-ignore:
      - 'CREDITS'
      - 'LICENSE'
      - 'NEWS.md'
      - 'README.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'CREDITS'
      - 'LICENSE'
      - 'NEWS.md'
      - 'README.md'

jobs:
  linux:
    name: Linux

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          ${CC} \
          automake \
          autoconf \
          libtool \
          flex \
          bison \
          libsqlite3-dev \
          libhyperscan-dev \
          # EOF
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure --with-shared-sqlite
    - name: make
      run: make -j2
    - name: make install
      run: make install
